/**
 * Imports real photos from /photos into the site.
 *
 * File naming (case-insensitive, .jpg .jpeg .png .webp .avif):
 *   <product-slug>.png, <product-slug>-1.png, <product-slug>-2.png …  → product gallery (in order)
 *   category-<category-slug>.png                                     → category tile
 *   hero.png                                                          → home hero banner (full image)
 *   hero-left.png, hero-center.png, hero-right.png                    → figures on the hero platforms
 *                                                                       (transparent PNG cut-outs look best)
 *   community-1.png … community-8.png                                 → home community strip
 *   home-video.mp4 (or .webm)                                         → looping home hero background video
 *
 * Copies matches to public/images/photos/ and rewrites src/data/photoManifest.ts.
 * Run with: npm run photos:import   (also regenerates supabase/seed.sql)
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { seedCategories, seedProducts } from '../src/data/seedProducts.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = resolve(root, 'photos');
const outDir = resolve(root, 'public/images/photos');
const EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.mp4', '.webm']);

if (!existsSync(srcDir)) {
  console.error('No /photos folder found. Create it and add images first.');
  process.exit(1);
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const productSlugs = new Set(seedProducts.map((p) => p.slug));
const categorySlugs = new Set(seedCategories.map((c) => c.slug));
const products: Record<string, Array<{ n: number; url: string }>> = {};
const categories: Record<string, string> = {};
const community: Array<{ n: number; url: string }> = [];
let hero: string | null = null;
let homeVideo: string | null = null;
const heroFigures: { left: string | null; center: string | null; right: string | null } = { left: null, center: null, right: null };
const unmatched: string[] = [];

for (const file of readdirSync(srcDir).sort()) {
  const ext = extname(file).toLowerCase();
  if (!EXT.has(ext)) continue;
  const base = file.slice(0, -ext.length).toLowerCase().trim().replace(/\s+/g, '-');
  const target = `${base}${ext}`;
  const url = `/images/photos/${target}`;
  let matched = true;

  const numbered = base.match(/^(.*)-(\d+)$/);
  if (base === 'home-video' && (ext === '.mp4' || ext === '.webm')) {
    homeVideo = url;
  } else if (ext === '.mp4' || ext === '.webm') {
    matched = false;
    unmatched.push(file);
  } else if (base === 'hero') {
    hero = url;
  } else if (base === 'hero-left' || base === 'hero-center' || base === 'hero-right') {
    heroFigures[base.slice(5) as 'left' | 'center' | 'right'] = url;
  } else if (base.startsWith('category-') && categorySlugs.has(base.slice(9))) {
    categories[base.slice(9)] = url;
  } else if (numbered && numbered[1] === 'community') {
    community.push({ n: Number(numbered[2]), url });
  } else if (productSlugs.has(base)) {
    (products[base] ??= []).push({ n: 0, url });
  } else if (numbered && productSlugs.has(numbered[1])) {
    (products[numbered[1]] ??= []).push({ n: Number(numbered[2]), url });
  } else {
    matched = false;
    unmatched.push(file);
  }
  if (matched) copyFileSync(resolve(srcDir, file), resolve(outDir, target));
}

const manifest = {
  products: Object.fromEntries(
    Object.entries(products).map(([slug, list]) => [slug, list.sort((a, b) => a.n - b.n).map((x) => x.url)]),
  ),
  categories,
  hero,
  heroFigures,
  homeVideo,
  community: community.sort((a, b) => a.n - b.n).map((x) => x.url),
};

writeFileSync(
  resolve(root, 'src/data/photoManifest.ts'),
  `/**
 * GENERATED by \`npm run photos:import\` — do not edit by hand.
 * Maps product/category slugs to real photos copied from /photos into /public/images/photos.
 * Anything missing here falls back to the generated placeholder artwork.
 */
export const photoManifest: {
  products: Record<string, string[]>;
  categories: Record<string, string>;
  hero: string | null;
  heroFigures: { left: string | null; center: string | null; right: string | null };
  homeVideo: string | null;
  community: string[];
} = ${JSON.stringify(manifest, null, 2)};
`,
  'utf8',
);

const missing = seedProducts.filter((p) => !manifest.products[p.slug]).map((p) => p.slug);
const missingCats = seedCategories.filter((c) => !categories[c.slug]).map((c) => c.slug);
console.log(`Imported photos for ${Object.keys(manifest.products).length}/${seedProducts.length} products, ${Object.keys(categories).length}/${seedCategories.length} categories, hero: ${hero ? 'yes' : 'no'}, hero figures: ${Object.values(heroFigures).filter(Boolean).length}/3, home video: ${homeVideo ? 'yes' : 'no'}, community: ${manifest.community.length}/8.`);
if (missing.length) console.log(`Still using placeholders (products): ${missing.join(', ')}`);
if (missingCats.length) console.log(`Still using placeholders (categories): ${missingCats.join(', ')}`);
if (unmatched.length) console.log(`Ignored (name doesn't match a product/category): ${unmatched.join(', ')}`);
