/**
 * GENERATED by `npm run photos:import` — do not edit by hand.
 * Maps product/category slugs to real photos copied from /photos into /public/images/photos.
 * Anything missing here falls back to the generated placeholder artwork.
 */
export const photoManifest: {
  products: Record<string, string[]>;
  categories: Record<string, string>;
  hero: string | null;
  heroFigures: { left: string | null; center: string | null; right: string | null };
  homeVideo: string | null;
  community: string[];
} = {
  "products": {},
  "categories": {},
  "hero": null,
  "heroFigures": {
    "left": null,
    "center": null,
    "right": null
  },
  "homeVideo": null,
  "community": []
};
